#!/bin/csh -f

if (-f $1.gcf)      mv -f $1.gcf GCF

if (-f $1.last.xyz) mv -f $1.last.xyz DYNl.xyz

if (-f $1.fra)      mv -f $1.fra FRAG

~/DoNOF_github/exe/DoNOFompg.x < $1.inp > $1.out

if(-f DYNl.xyz) mv -f DYNl.xyz  $1.last.xyz

if(-f DYN.xyz)  mv -f DYN.xyz   $1.xyz

if(-f endyn.dat)  mv -f endyn.dat $1.endyn.dat

if (-f APSG)    mv -f APSG      $1.pun

if (-f 1DM)     mv -f 1DM       $1.1dm

if (-f 2DM)     mv -f 2DM       $1.2dm

if (-f N2DM)    mv -f N2DM      $1.n2dm

if (-f CJK)     mv -f CJK       $1.cjk

if (-f CND)     mv -f CND       $1.cnd

if (-f Tijab)   mv -f Tijab     $1.2mp

if (-f FRAG)    mv -f FRAG      $1.fra

if (-f GCFe)    mv -f GCFe      $1.gcfe

if (-f GCF)     mv -f GCF       $1.gcf

if (-f CGGRAD)  mv -f CGGRAD    $1.cgo

if (-f WFN)     mv -f WFN       $1.wfn

if (-f FCHK)    mv -f FCHK      $1.fchk

if (-f MLD)then
 cp -f MLD $1.mld
 if (-f XYZ)then
  cat MLD XYZ > $1.mld
  rm -f XYZ
 endif
 rm -f MLD
endif

### remove

if (-f CGM)     rm -f CGM

if (-f BFST)    rm -f BFST

if (-f fort.1)  rm -f fort.1
